
import { Scenario } from './types';

// Helper to generate IDs
let idCounter = 0;
const create = (text: string, verdict: 'Nice' | 'Naughty', reason: string, illustration: string): Scenario => ({
  id: ++idCounter,
  text,
  verdict,
  reason,
  illustration
});

export const TOTAL_ROUNDS = 10;

export const SCENARIOS: Scenario[] = [
  // --- CLASSIC NICE (0-50) ---
  create("Shared their favorite toy with a crying sibling", "Nice", "Sharing is caring!", "🧸"),
  create("Helped Grandma cross the icy street", "Nice", "Classic good deed.", "👵"),
  create("Cleaned their room without being asked", "Nice", "A rare miracle.", "🧹"),
  create("Ate all their vegetables (even the broccoli)", "Nice", "Healthy habits.", "🥦"),
  create("Finished homework before playing video games", "Nice", "Priorities in order.", "📝"),
  create("Brushed their teeth for the full two minutes", "Nice", "Dental hygiene superstar.", "🪥"),
  create("Fed the dog on time every day", "Nice", "Responsible pet owner.", "🐶"),
  create("Made their bed this morning", "Nice", "Starting the day right.", "🛏️"),
  create("Said 'Please' and 'Thank You' at dinner", "Nice", "Manners matter.", "🍽️"),
  create("Held the door open for a stranger", "Nice", "Chivalry lives.", "🚪"),
  create("Donated allowance to the animal shelter", "Nice", "Charitable heart.", "🐾"),
  create("Drew a beautiful picture for Mom", "Nice", "Artistic affection.", "🎨"),
  create("Saved up money to buy Dad a gift", "Nice", "Fiscal responsibility.", "💰"),
  create("Rescued a lost kitten from a tree", "Nice", "Heroic effort.", "🐱"),
  create("Watered the neighbor's plants while they were away", "Nice", "Good neighbor etiquette.", "🪴"),
  create("Recycled all the cardboard boxes", "Nice", "Eco-friendly warrior.", "♻️"),
  create("Picked up trash at the local park", "Nice", "Community service.", "🗑️"),
  create("Comforted a friend who scraped their knee", "Nice", "Empathy in action.", "🩹"),
  create("Told the truth even when it was hard", "Nice", "Honesty is the best policy.", "🤥"),
  create("Apologized to their sister for breaking a doll", "Nice", "Taking responsibility.", "🤝"),
  create("Hugged Dad when he looked sad", "Nice", "Emotional intelligence.", "🫂"),
  create("Shared their Halloween candy", "Nice", "Sweet sacrifice.", "🍬"),
  create("Read a book instead of watching TV", "Nice", "Brain power.", "📖"),
  create("Practiced piano without complaining", "Nice", "Dedication to the arts.", "🎹"),
  create("Went to bed on time without a fuss", "Nice", "Dreamer.", "😴"),
  create("Wore their helmet while biking", "Nice", "Safety first.", "🚲"),
  create("Put away the laundry", "Nice", "Helper elf in training.", "🧺"),
  create("Set the table for Thanksgiving dinner", "Nice", "Holiday helper.", "🦃"),
  create("Dried the dishes after dinner", "Nice", "Chore champion.", "🍽️"),
  create("Folded their own clothes", "Nice", "Independence.", "👕"),
  create("Tied their own shoes", "Nice", "Big kid skills.", "👟"),
  create("Wrote a letter to Grandma", "Nice", "Keeping in touch.", "✉️"),
  create("Made a new friend at school", "Nice", "Social butterfly.", "👋"),
  create("Included the lonely kid in the game", "Nice", "Inclusivity.", "⚽"),
  create("Complimented the teacher's outfit", "Nice", "Flattery gets you everywhere.", "🍎"),
  create("Returned a lost wallet", "Nice", "Integrity.", "👛"),
  create("Followed the pool rules", "Nice", "Rule follower.", "🏊"),
  create("Waited their turn for the slide", "Nice", "Patience.", "🛝"),
  create("Listened to the babysitter", "Nice", "Respect for authority.", "👂"),
  create("Took a bath without splashing water everywhere", "Nice", "Clean and dry.", "🛁"),
  create("Ate an apple instead of chips", "Nice", "Healthy choice.", "🍎"),
  create("Drank a whole glass of milk", "Nice", "Strong bones.", "🥛"),
  create("Helped tie a little kid's shoe", "Nice", "Mentorship.", "👟"),
  create("Built a birdhouse", "Nice", "Nature lover.", "🐦"),
  create("Gave flowers to the bus driver", "Nice", "Appreciation.", "💐"),
  create("Smiled at a grumpy person", "Nice", "Spreading joy.", "😊"),
  create("Learned a new word", "Nice", "Vocabulary expansion.", "📚"),
  create("Shared their umbrella in the rain", "Nice", "Protector.", "☔"),
  create("Walked the dog without being asked", "Nice", "Initiative.", "🐕"),
  create("Baked cookies for the fire station", "Nice", "Community gratitude.", "🍪"),

  // --- CLASSIC NAUGHTY (51-100) ---
  create("Pulled their sister's pigtails", "Naughty", "Hair raising behavior.", "👧"),
  create("Stuck their tongue out at the mailman", "Naughty", "Rude gesture.", "😝"),
  create("Rolled their eyes at Mom", "Naughty", "Attitude problem.", "🙄"),
  create("Slammed the bedroom door", "Naughty", "Dramatic exit.", "🚪"),
  create("Yelled 'I hate broccoli!' at dinner", "Naughty", "Vegetable slander.", "🥦"),
  create("Hid Brussel sprouts in the milk carton", "Naughty", "Ruined the milk.", "🥛"),
  create("Fed the dog chocolate", "Naughty", "Dangerous for the pup!", "🍫"),
  create("Drew a mural on the wall with permanent marker", "Naughty", "Unauthorized renovation.", "🖍️"),
  create("Cut their own hair with safety scissors", "Naughty", "Bad barber skills.", "✂️"),
  create("Broke Mom's favorite vase", "Naughty", "Clumsy destruction.", "🏺"),
  create("Spilled grape juice on the white carpet", "Naughty", "Permanent stain.", "🍷"),
  create("Jumped on the bed until it broke", "Naughty", "Mattress mayhem.", "🛏️"),
  create("Started a fistfight with a sibling", "Naughty", "Domestic dispute.", "🥊"),
  create("Stole a cookie from the jar", "Naughty", "Petty theft.", "🍪"),
  create("Lied about brushing their teeth", "Naughty", "Minty deception.", "🤥"),
  create("Didn't flush the toilet", "Naughty", "Hygiene fail.", "🚽"),
  create("Left the toilet seat up", "Naughty", "A cold surprise at night.", "🚽"),
  create("Wiped chocolate hands on the curtains", "Naughty", "Drapery disaster.", "🍫"),
  create("Tracked mud through the kitchen", "Naughty", "Messy footprints.", "👣"),
  create("Played baseball inside the house", "Naughty", "Indoor hazard.", "⚾"),
  create("Teased the cat with a laser pointer for hours", "Naughty", "Feline frustration.", "🐈"),
  create("Chased the ducks at the park", "Naughty", "Wildlife harassment.", "🦆"),
  create("Threw a tantrum in the grocery store", "Naughty", "Aisle 4 meltdown.", "🛒"),
  create("Cried because they wanted candy", "Naughty", "Sugar tears.", "🍭"),
  create("Refused to take a nap", "Naughty", "Sleep resistance.", "😫"),
  create("Stayed up past bedtime playing DS", "Naughty", "Sleep deprivation.", "🎮"),
  create("Snuck out of the house at night", "Naughty", "Escape artist.", "🌙"),
  create("Hid the TV remote", "Naughty", "Power play.", "📺"),
  create("Changed the channel during the Super Bowl", "Naughty", "Sports sabotage.", "🏈"),
  create("Burped the alphabet loudly", "Naughty", "Gastrointestinal performance.", "🗣️"),
  create("Farted on their brother's pillow", "Naughty", "Pink eye risk.", "💨"),
  create("Picked their nose in public", "Naughty", "Gold digging.", "👆"),
  create("Ate a booger", "Naughty", "Self-cannibalism?", "🤢"),
  create("Chewed with their mouth open", "Naughty", "See-food diet.", "👄"),
  create("Slurped soup really loud", "Naughty", "Sound effects included.", "🍜"),
  create("Interrupted adults talking", "Naughty", "Impatient chatterbox.", "🗣️"),
  create("Ran with scissors", "Naughty", "Safety hazard.", "✂️"),
  create("Played with matches", "Naughty", "Fire hazard.", "🔥"),
  create("Touched wet paint", "Naughty", "Smudged masterpiece.", "🎨"),
  create("Unraveled the entire toilet paper roll", "Naughty", "TP party.", "🧻"),
  create("Squeezed all the toothpaste into the sink", "Naughty", "Minty mess.", "🦷"),
  create("Put gum in their sister's hair", "Naughty", "Sticky situation.", "💇‍♀️"),
  create("Put glue on the teacher's chair", "Naughty", "Classic prank.", "🪑"),
  create("Put a frog in their pocket", "Naughty", "Amphibian abduction.", "🐸"),
  create("Put worms in the salad", "Naughty", "Extra protein?", "🪱"),
  create("Wore a scary mask to church", "Naughty", "Holy terror.", "👺"),
  create("Prank called the pizza place", "Naughty", "Wasted pepperoni time.", "🍕"),
  create("Ding dong ditched the neighbors", "Naughty", "Doorbell dash.", "🚪"),
  create("Had a water balloon fight inside", "Naughty", "Indoor flood.", "🎈"),
  create("Refused to take a bath for a week", "Naughty", "Smelly rebellion.", "🚿"),

  // --- MODERN / TECH (101-150) ---
  create("Taught Grandpa how to use Zoom", "Nice", "Tech support.", "💻"),
  create("Liked all of Mom's Facebook posts", "Nice", "Social validation.", "👍"),
  create("Didn't spoil the movie ending", "Nice", "Spoiler free zone.", "🎬"),
  create("Paused their online game for dinner", "Nice", "Impossible sacrifice.", "🎮"),
  create("Charged Dad's phone for him", "Nice", "Battery savior.", "🔋"),
  create("Fixed the Wi-Fi router", "Nice", "IT Hero.", "📶"),
  create("Let little sibling be Player 1", "Nice", "Controller charity.", "🎮"),
  create("Shared Netflix password with a friend", "Nice", "Streaming generosity.", "📺"),
  create("Texted back immediately", "Nice", "Prompt communication.", "📱"),
  create("Put the phone away at the dinner table", "Nice", "Digital detox.", "🍽️"),
  create("Used headphones on the bus", "Nice", "Audio consideration.", "🎧"),
  create("Reported a cyberbully", "Nice", "Digital justice.", "🛡️"),
  create("Left a nice comment on a YouTube video", "Nice", "Comment section positivity.", "💬"),
  create("Subscribed to a educational channel", "Nice", "Brain gain.", "▶️"),
  create("Upvoted good artwork on Reddit", "Nice", "Supporting creators.", "⬆️"),
  create("Fact-checked before sharing a rumor", "Nice", "Stopping fake news.", "🕵️"),
  create("Cited sources in their essay", "Nice", "Academic integrity.", "📄"),
  create("Helped set up the printer", "Nice", "The hardest task known to man.", "🖨️"),
  create("Coded a simple game", "Nice", "Future engineer.", "💻"),
  create("Made digital art for a friend", "Nice", "Pixel painter.", "🎨"),
  create("Started a wholesome viral dance", "Nice", "Trendsetter.", "💃"),
  create("Started an online petition for trees", "Nice", "Activism.", "🌲"),
  create("Donated crypto to charity", "Nice", "Modern philanthropy.", "🪙"),
  create("Had a tidy Zoom background", "Nice", "Virtual cleanliness.", "📹"),
  create("Muted mic when chewing snacks", "Nice", "Audio etiquette.", "🎙️"),
  create("Deleted Dad's 100-hour save file", "Naughty", "Digital murder.", "💾"),
  create("Spent $500 on Fortnite skins", "Naughty", "Credit card theft.", "💳"),
  create("Forgot the Netflix password", "Naughty", "Locked out.", "🔒"),
  create("Violated screen time rules", "Naughty", "Blue light addiction.", "📱"),
  create("Trolled people in comments", "Naughty", "Keyboard warrior.", "⌨️"),
  create("Disliked a puppy video", "Naughty", "Heartless.", "👎"),
  create("Spammed the group chat", "Naughty", "Notification overload.", "🔔"),
  create("Rage quit a team game", "Naughty", "Bad sport.", "🤬"),
  create("Broke the controller in anger", "Naughty", "Hardware destruction.", "🎮"),
  create("Dropped Mom's phone in the toilet", "Naughty", "Water damage.", "🚽"),
  create("Prank texted the wrong number", "Naughty", "Confusing strangers.", "📱"),
  create("Rickrolled the teacher during class", "Naughty", "Never gonna give you up.", "🎵"),
  create("Hacked sibling's Roblox account", "Naughty", "Identity theft.", "🤖"),
  create("Changed phone language to Klingon", "Naughty", "Qapla'!", "👽"),
  create("Asked Alexa to fart 50 times", "Naughty", "AI abuse.", "🔈"),
  create("Played loud music on the bus speaker", "Naughty", "Public nuisance.", "🔊"),
  create("Took a selfie at a funeral", "Naughty", "Inappropriate timing.", "🤳"),
  create("Ghosted their best friend", "Naughty", "Disappearing act.", "👻"),
  create("Catfished someone online", "Naughty", "Digital deception.", "🐟"),
  create("Stole the neighbor's Wi-Fi", "Naughty", "Bandwidth bandit.", "📶"),
  create("Pirated a movie", "Naughty", "Copyright infringement.", "🏴‍☠️"),
  create("Tweeted a movie spoiler", "Naughty", "Ruining the plot.", "🐦"),
  create("Used a funny filter during serious class", "Naughty", "Potato face.", "🥔"),
  create("Spread fake news", "Naughty", "Misinformation.", "📰"),
  create("Used ChatGPT to write their whole essay", "Naughty", "AI Plagiarism.", "🤖"),

  // --- FUNNY / WEIRD (151-200) ---
  create("Mailed themselves to the North Pole", "Naughty", "Return to sender.", "📦"),
  create("Wrapped the cat in toilet paper", "Naughty", "Mummy cat.", "🐈"),
  create("Used salt instead of sugar in cake", "Naughty", "Salty surprise.", "🎂"),
  create("Tried to vacuum the lawn", "Naughty", "Yard work confusion.", "🚜"),
  create("Wrote a letter asking for World Peace", "Nice", "Miss America answer.", "🕊️"),
  create("Put googly eyes on everything in the fridge", "Nice", "Edible comedy.", "👀"),
  create("Filled boots with shaving cream", "Naughty", "Santa surprise.", "🎅"),
  create("Made a slip-n-slide with cooking oil", "Naughty", "Greased lightning.", "🛢️"),
  create("Protested bedtime with signs", "Naughty", "Civil unrest.", "🪧"),
  create("Paid for candy with Monopoly money", "Naughty", "Counterfeit cash.", "💵"),
  create("Washed the car with a rock", "Naughty", "Exfoliating the paint.", "🪨"),
  create("Adopted a pet rock", "Nice", "Low maintenance.", "🗿"),
  create("Glued a quarter to the sidewalk", "Naughty", "Pranking pedestrians.", "🪙"),
  create("Made a friendship bracelet for the mailman", "Nice", "Postal love.", "📿"),
  create("Used curtains as a superhero cape", "Naughty", "Fabric damage.", "🦸"),
  create("Tried to flush a goldfish to 'freedom'", "Naughty", "Finding Nemo gone wrong.", "🐠"),
  create("Built a nuclear reactor in the basement", "Naughty", "Sheldon Cooper vibes.", "☢️"),
  create("Taught the parrot to curse", "Naughty", "Profane bird.", "🦜"),
  create("Replaced Oreo cream with toothpaste", "Naughty", "Minty prank.", "🍪"),
  create("Gave their lunch to a squirrel", "Nice", "Feeding wildlife.", "🐿️"),
  create("Wore underwear on the outside", "Naughty", "Captain Underpants.", "🩲"),
  create("Ate a glue stick", "Naughty", "Sticky stomach.", "🥢"),
  create("Licked a frozen pole", "Naughty", "Stuck tongue.", "❄️"),
  create("Stuck a bean in their ear", "Naughty", "ER visit waiting to happen.", "👂"),
  create("Cut their bangs too short", "Naughty", "Forehead exposure.", "✂️"),
  create("Painted the dog blue", "Naughty", "Blue's Clues IRL.", "🎨"),
  create("Tried to sell their sister", "Naughty", "Human trafficking is bad.", "🏷️"),
  create("Ran away to the backyard tent", "Naughty", "Short lived rebellion.", "⛺"),
  create("Built a fort using every pillow in the house", "Nice", "Architectural genius.", "🏰"),
  create("Played 'The Floor is Lava' and broke a lamp", "Naughty", "Lava damage.", "🌋"),
  create("Blamed the imaginary friend", "Naughty", "Scapegoat.", "👻"),
  create("Tried to dig a hole to China", "Nice", "Ambitious civil engineering.", "🌏"),
  create("Ate a dog treat", "Naughty", "Barking mad.", "🦴"),
  create("Drank pickle juice from the jar", "Naughty", "Briney beverage.", "🥒"),
  create("Put ketchup on pancakes", "Naughty", "Culinary crime.", "🥞"),
  create("Wore mismatched socks on purpose", "Nice", "Fashion statement.", "🧦"),
  create("Opened a barber shop for dolls", "Naughty", "Bald barbies.", "💇"),
  create("Made a dress out of toilet paper", "Nice", "Project Runway.", "👗"),
  create("Super glued their fingers together", "Naughty", "Sticky situation.", "🖐️"),
  create("Put Mentos in Diet Coke in the living room", "Naughty", "Explosive carpet.", "🍾"),
  create("Tried to ride the dog like a horse", "Naughty", "Animal cruelty.", "🐕"),
  create("Wore a pot on head as a helmet", "Nice", "Knight in shining armor.", "🍳"),
  create("Spoke only in meows for a day", "Naughty", "Cat communication.", "🐱"),
  create("Tried to hatch a chicken egg from the fridge", "Nice", "Biology experiment.", "🥚"),
  create("Made 'potion' with shampoo and lotion", "Naughty", "Bathroom alchemy.", "🧪"),
  create("Put stickers on the cat", "Naughty", "Feline graffiti.", "🐈"),
  create("Tried to microwave a spoon", "Naughty", "Spark show.", "⚡"),
  create("Ate snow (yellow snow)", "Naughty", "Don't eat that.", "❄️"),
  create("Put soap in the fountain", "Naughty", "Bubble trouble.", "🫧"),
  create("Climbed the roof to see Santa", "Naughty", "Dangerous outlook.", "🏠"),

  // --- SCHOOL DAYS (201-250) ---
  create("Got an A+ on the math test", "Nice", "Mathlete.", "💯"),
  create("Failed math but tried hard", "Nice", "Effort counts.", "➗"),
  create("Forgot homework at home", "Naughty", "Memory lapse.", "🎒"),
  create("Claimed the dog ate the homework (Lie)", "Naughty", "Classic excuse.", "🐶"),
  create("Dog actually ate the homework", "Nice", "Unfortunate truth.", "📄"),
  create("Acted as the class clown", "Naughty", "Disruptive humor.", "🤡"),
  create("Fell asleep in class", "Naughty", "Boring lecture.", "💤"),
  create("Passed a note to a crush", "Naughty", "Old school texting.", "💌"),
  create("Cheated on the spelling test", "Naughty", "Dishonest scholar.", "📝"),
  create("Copied a friend's answers", "Naughty", "Plagiarism.", "👀"),
  create("Brought an apple for the teacher", "Nice", "Teacher's pet.", "🍎"),
  create("Stayed after to clean the blackboard", "Nice", "Helper.", "🧽"),
  create("Raised hand before speaking", "Nice", "Respectful participation.", "✋"),
  create("Cut in the lunch line", "Naughty", "Line jumper.", "🍔"),
  create("Shared lunch with a kid who forgot theirs", "Nice", "Lunch hero.", "🥪"),
  create("Started a food fight", "Naughty", "Cafeteria chaos.", "🍕"),
  create("Stuck gum under the desk", "Naughty", "Gross furniture.", "🍬"),
  create("Swung back on the chair", "Naughty", "Gravity risk.", "🪑"),
  create("Corrected the teacher's grammar", "Naughty", "Smarty pants.", "🤓"),
  create("Lost a library book", "Naughty", "Overdue fines.", "📚"),
  create("Was late for the bus", "Naughty", "Running late.", "🚌"),
  create("Missed the school bus entirely", "Naughty", "Hooky potential.", "🛑"),
  create("Had perfect attendance", "Nice", "Iron immune system.", "📅"),
  create("Won the spelling bee", "Nice", "Linguistic champion.", "🐝"),
  create("Forgot gym clothes", "Naughty", "Bench warmer.", "🎽"),
  create("Left a banana in the locker all year", "Naughty", "Biohazard.", "🍌"),
  create("Made a volcano for the science fair", "Nice", "Explosive science.", "🌋"),
  create("Stood up for a kid being bullied", "Nice", "Brave defender.", "🛡️"),
  create("Was the Hall Monitor", "Nice", "Law enforcement.", "👮"),
  create("Forged Mom's signature", "Naughty", "Forgery.", "✍️"),
  create("Ran in the hallways", "Naughty", "Speed demon.", "🏃"),
  create("Pulled the fire alarm", "Naughty", "False alarm felony.", "🚨"),
  create("Shared answers during a test", "Naughty", "Accomplice.", "🤝"),
  create("Helped clean up a spill", "Nice", "Janitorial aid.", "🧹"),
  create("Sharpened pencils for everyone", "Nice", "Pointy kindness.", "✏️"),
  create("Read aloud to the class", "Nice", "Public speaking.", "📖"),
  create("Lost their backpack", "Naughty", "Misplaced gear.", "🎒"),
  create("Traded a healthy lunch for candy", "Naughty", "Sugar economy.", "🍬"),
  create("Made fun of a substitute teacher", "Naughty", "Disrespectful.", "👨‍🏫"),
  create("Organized a study group", "Nice", "Academic leader.", "📚"),
  create("Doodled on the desk", "Naughty", "Vandalism.", "🖊️"),
  create("Threw a paper airplane", "Naughty", "Air traffic violation.", "✈️"),
  create("Recited a poem perfectly", "Nice", "Poet laureate.", "🎭"),
  create("Helped a new student find class", "Nice", "Tour guide.", "🗺️"),
  create("Snuck snacks into class", "Naughty", "Contraband.", "🥨"),
  create("Used a calculator on a non-calculator test", "Naughty", "Cheater cheater pumpkin eater.", "🧮"),
  create("Wrote a play for the talent show", "Nice", "Playwright.", "🎭"),
  create("Stayed quiet during reading time", "Nice", "Library voice.", "🤫"),
  create("Cleaned the hamster cage", "Nice", "Class pet care.", "🐹"),
  create("Forgot to study for the big test", "Naughty", "Unprepared.", "📉"),

  // --- OUTDOORS / NATURE (251-280) ---
  create("Caught a firefly and let it go", "Nice", "Catch and release.", "萤"),
  create("Squashed a bug on purpose", "Naughty", "Insecticide.", "🐛"),
  create("Picked the neighbor's prize roses", "Naughty", "Garden theft.", "🌹"),
  create("Climbed a tree too high", "Naughty", "Rescue required.", "🌳"),
  create("Made mud pies", "Nice", "Culinary arts (dirt).", "🥧"),
  create("Threw a snowball at someone's face", "Naughty", "Ice attack.", "❄️"),
  create("Built a masterpiece sandcastle", "Nice", "Beach architect.", "🏰"),
  create("Knocked down someone else's sandcastle", "Naughty", "Beach bully.", "🏖️"),
  create("Littered a candy wrapper", "Naughty", "Polluter.", "🗑️"),
  create("Saved a worm from the sidewalk", "Nice", "Worm savior.", "🪱"),
  create("Chased a squirrel", "Naughty", "Rodent pursuit.", "🐿️"),
  create("Barked back at a dog", "Naughty", "Cross-species argument.", "🐕"),
  create("Got stung trying to catch a bee", "Naughty", "Risky business.", "🐝"),
  create("Sang songs around a campfire", "Nice", "Musical bonding.", "🔥"),
  create("Peed in the swimming pool", "Naughty", "Chlorine reaction.", "🏊"),
  create("Did a cannonball and splashed everyone", "Naughty", "Tsunami maker.", "💦"),
  create("Refused to wear sunscreen", "Naughty", "Sunburn regret.", "☀️"),
  create("Helped plant a community garden", "Nice", "Green thumb.", "🥕"),
  create("Threw rocks at a beehive", "Naughty", "Swarm danger.", "🐝"),
  create("Carved initials into a tree", "Naughty", "Bark graffiti.", "🔪"),
  create("Cleaned up dog poop", "Nice", "Scoop the poop.", "💩"),
  create("Fed ducks bread (it's bad for them!)", "Naughty", "Nutritional mistake.", "🦆"),
  create("Fed ducks peas (it's good for them!)", "Nice", "Bird dietician.", "🟢"),
  create("Caught a frog", "Nice", "Nature explorer.", "🐸"),
  create("Let the frog go", "Nice", "Freedom.", "🐸"),
  create("Threw a rock through a window", "Naughty", "Vandalism.", "🪟"),
  create("Mowed the lawn", "Nice", "Landscaper.", "🌱"),
  create("Raked leaves", "Nice", "Fall chores.", "🍂"),
  create("Jumped in the leaf pile", "Nice", "Fall fun.", "🍁"),
  create("Scattered the leaf pile", "Naughty", "Undo work.", "🌬️"),

  // --- HOLIDAY SPECIFIC (281-310) ---
  create("Peeked at Christmas presents", "Naughty", "Spoiler.", "🎁"),
  create("Shook the boxes to guess the gift", "Naughty", "Package damage.", "📦"),
  create("Ate cookies meant for Santa", "Naughty", "Stole from Santa.", "🍪"),
  create("Left carrots for the reindeer", "Nice", "Animal hospitality.", "🥕"),
  create("Tangled the Christmas lights", "Naughty", "Knotty problem.", "💡"),
  create("Broke a vintage ornament", "Naughty", "Heirloom loss.", "🎄"),
  create("Sang carols very loudly", "Nice", "Festive spirit.", "🎶"),
  create("Wore an ugly sweater with pride", "Nice", "Fashion confidence.", "🧥"),
  create("Re-gifted a fruitcake", "Naughty", "The gift that keeps giving.", "🍞"),
  create("Sent thank you notes late", "Naughty", "Delayed gratitude.", "📝"),
  create("Built a snowman", "Nice", "Frosty friend.", "⛄"),
  create("Knocked over the Christmas tree", "Naughty", "Timber!", "🎄"),
  create("Put the cat in a stocking", "Naughty", "Unhappy kitty.", "🧦"),
  create("Unwrapped a gift early", "Naughty", "Impatience.", "🎁"),
  create("Asked for coal ironically", "Naughty", "Hipster kid.", "🌑"),
  create("Helped decorate the tree", "Nice", "Deck the halls.", "⭐"),
  create("Ate all the advent calendar chocolates at once", "Naughty", "Calendar confusion.", "🍫"),
  create("Left milk out until it spoiled", "Naughty", "Sour surprise.", "🥛"),
  create("Wrote a wish list 10 pages long", "Naughty", "Greedy.", "📜"),
  create("Donated old toys before Christmas", "Nice", "Making room.", "🧸"),
  create("Kissed under the mistletoe", "Nice", "Romance.", "🌿"),
  create("Put antlers on the dog", "Nice", "Max the reindeer.", "🦌"),
  create("Hid the elf on the shelf", "Naughty", "Hide and seek.", "🧝"),
  create("Touched the elf on the shelf", "Naughty", "Magic loss.", "🚫"),
  create("Stayed awake to catch Santa", "Naughty", "Spying.", "👀"),
  create("Made a gingerbread house", "Nice", "Candy architect.", "🏠"),
  create("Ate the gingerbread house walls", "Naughty", "Structural failure.", "🍬"),
  create("Wore jingle bells on shoes", "Nice", "Jingly walker.", "🔔"),
  create("Gave a gift to the mailman", "Nice", "Tipping.", "🎁"),
  create("Spread holiday cheer", "Nice", "Joy to the world.", "✨"),

  // --- MISC / FINAL MIX (311-330) ---
  create("Used a whoopee cushion on Grandma", "Naughty", "Flatulence prank.", "💨"),
  create("Put a fake spider in the bathroom", "Naughty", "Arachnophobia.", "🕷️"),
  create("Gave a wet willy", "Naughty", "Slobbery ear.", "👂"),
  create("Gave a noogie", "Naughty", "Headlock.", "👊"),
  create("Tattled on a sibling for nothing", "Naughty", "Snitch.", "🗣️"),
  create("Kept a secret promise", "Nice", "Trustworthy.", "🤫"),
  create("Broke a pinky promise", "Naughty", "Betrayal.", "🤙"),
  create("Crossed fingers while lying", "Naughty", "Perjury.", "🤞"),
  create("Jinxed a friend", "Naughty", "Curse.", "🤐"),
  create("Played punch buggy way too hard", "Naughty", "Bruiser.", "🚗"),
  create("Made fun of someone's name", "Naughty", "Bully behavior.", "📛"),
  create("Gave someone a cool nickname", "Nice", "Endearment.", "😎"),
  create("Ate pizza crusts first", "Nice", "Weird but okay.", "🍕"),
  create("Played with food", "Naughty", "Messy eater.", "🍝"),
  create(" joined the 'Clean Plate Club'", "Nice", "Zero waste.", "🍽️"),
  create("Asked for seconds", "Nice", "Compliments to the chef.", "🍲"),
  create("Burnt the toast", "Naughty", "Kitchen smoke.", "🍞"),
  create("Made breakfast in bed for Mom", "Nice", "Room service.", "🍳"),
  create("Spilled hot coffee", "Naughty", "Scalding hazard.", "☕"),
  create("Walked backwards all day", "Naughty", "Reverse hazard.", "🔙"),
];

// Shuffle helper
export const getShuffledScenarios = () => {
  return [...SCENARIOS].sort(() => Math.random() - 0.5);
};

// Level 2 Gifts
export const GOOD_GIFTS = [
    { text: "Super Action Hero", icon: "🦸‍♂️" },
    { text: "Shiny Red Bicycle", icon: "🚲" },
    { text: "Video Game Console", icon: "🎮" },
    { text: "Giant Teddy Bear", icon: "🧸" },
    { text: "Chemistry Set", icon: "🧪" },
    { text: "Electric Guitar", icon: "🎸" },
    { text: "Soccer Ball", icon: "⚽" },
    { text: "Art Supplies", icon: "🎨" },
    { text: "Rocket Ship Model", icon: "🚀" },
    { text: "Train Set", icon: "🚂" },
    { text: "Dollhouse", icon: "🏠" },
    { text: "Telescope", icon: "🔭" },
    { text: "Skateboard", icon: "🛹" },
    { text: "Tablet", icon: "📱" },
    { text: "Puppy", icon: "🐶" },
    { text: "Kitten", icon: "🐱" },
    { text: "Drum Set", icon: "🥁" },
    { text: "Magic Kit", icon: "🎩" },
    { text: "Basketball Hoop", icon: "🏀" },
    { text: "Robot Kit", icon: "🤖" }
];

export const BAD_GIFTS = [
    { text: "Lump of Coal", icon: "🌑" },
    { text: "Leftover Broccoli", icon: "🥦" },
    { text: "Old Sock", icon: "🧦" },
    { text: "Spider in a Box", icon: "🕷️" },
    { text: "Empty Cardboard Box", icon: "📦" },
    { text: "Broken Pencil", icon: "✏️" },
    { text: "Rotten Egg", icon: "🥚" },
    { text: "Tangled Wires", icon: "🔌" },
    { text: "Bag of Trash", icon: "🗑️" },
    { text: "Homework Assignment", icon: "📝" },
    { text: "Onion", icon: "🧅" },
    { text: "Used Tissue", icon: "🤧" },
    { text: "Jar of Dirt", icon: "🫙" },
    { text: "Dead Battery", icon: "🔋" },
    { text: "Rusty Spoon", icon: "🥄" },
    { text: "Fruitcake", icon: "🍞" },
    { text: "Soggy Sandwich", icon: "🥪" },
    { text: "Toothbrush (Plain)", icon: "🪥" },
    { text: "Instruction Manual", icon: "📖" },
    { text: "Potato", icon: "🥔" }
];
