import { Scenario } from './types';

// Helper to generate IDs
let idCounter = 0;
const create = (text: string, verdict: 'Nice' | 'Naughty', reason: string, illustration: string): Scenario => ({
  id: ++idCounter,
  text,
  verdict,
  reason,
  illustration
});

export const TOTAL_ROUNDS = 10;

export const SCENARIOS: Scenario[] = [
  // --- CHILDHOOD CLASSICS ---
  create("Shared their favorite toy with a crying sibling", "Nice", "Sharing is caring!", "🧸"),
  create("Ate all the cookies before dinner", "Naughty", "Ruined their appetite and stole from the cookie jar.", "🍪"),
  create("Drew a 'mural' on the living room wall with permanent marker", "Naughty", "Artistic expression, but property damage.", "🖍️"),
  create("Helped Grandma cross the icy street", "Nice", "Classic good deed.", "👵"),
  create("Put a frog in their sister's bed", "Naughty", "Terrifying for the sister, funny for the frog.", "🐸"),
  create("Cleaned their room without being asked", "Nice", "A rare miracle.", "🧹"),
  create("Fed the dog their broccoli under the table", "Naughty", "Deceptive vegetable disposal.", "🥦"),
  create("Made a handmade card for Mother's Day", "Nice", "Thoughtful and creative.", "💌"),
  create("Tied the teacher's shoelaces together", "Naughty", "A tripping hazard.", "👟"),
  create("Saved allowance to buy a gift for a friend", "Nice", "Fiscal responsibility and generosity.", "💰"),
  create("Threw a tantrum in the grocery store because of candy", "Naughty", "Eardrum damage for everyone.", "📢"),
  create("Helped a lost kitten find its way home", "Nice", "Animal rescue hero.", "🐱"),
  create("Refused to take a bath for a week", "Naughty", "Stinky behavior.", "🛁"),
  create("Planted a tree in the backyard", "Nice", "Helping the environment.", "🌳"),
  create("Cut their own hair with safety scissors", "Naughty", "Now they look like a patchy lawn.", "✂️"),
  create("Donated old toys to charity", "Nice", "Spread the joy.", "🎁"),
  create("Burped the alphabet at the dinner table", "Naughty", "Impressive, but rude.", "💨"),
  create("Watered the neighbor's plants while they were away", "Nice", "Good neighbor etiquette.", "🪴"),
  create("Hid Brussel sprouts in the milk carton", "Naughty", "Ruined the milk and the dinner.", "🥛"),
  create("Read a bedtime story to a younger cousin", "Nice", "Literacy promotion.", "📖"),
  
  // --- FUNNY / WEIRD ---
  create("Tried to flush a goldfish to 'freedom' (the ocean)", "Naughty", "Good intentions, bad plumbing execution.", "🐠"),
  create("Built a nuclear reactor in the basement", "Naughty", "Too dangerous for a 9-year-old.", "☢️"),
  create("Taught the parrot to say curse words", "Naughty", "Polly shouldn't say that.", "🦜"),
  create("Replaced the Oreo cream with toothpaste", "Naughty", "A minty fresh betrayal.", "🦷"),
  create("Attempted to mail themselves to the North Pole", "Nice", "They just really wanted to see us!", "📮"),
  create("Wrapped the cat in toilet paper to make a 'mummy'", "Naughty", "The cat did not consent.", "🐈"),
  create("Baked a cake using salt instead of sugar", "Naughty", "An unintentional prank.", "🧂"),
  create("Tried to vacuum the lawn", "Nice", "They were trying to help clean up nature?", "🚜"),
  create("Wrote a letter to Santa asking for peace on earth", "Nice", "Aww, big picture thinking.", "📜"),
  create("Put googly eyes on every item in the fridge", "Nice", "Comedy gold.", "👀"),
  create("Filled the dad's boots with shaving cream", "Naughty", "Squelchy feet.", "👢"),
  create("Created a slip-n-slide in the hallway with cooking oil", "Naughty", "Safety hazard!", "🌊"),
  create("Organized a protest against bedtime", "Naughty", "Civil disobedience.", "🪧"),
  create("Gave their lunch to a hungry friend", "Nice", "Selfless act.", "🥪"),
  create("Tried to pay for candy with Monopoly money", "Naughty", "Counterfeit currency.", "💵"),
  create("Washed the car with a rock", "Naughty", "Scratched the paint job.", "🪨"),
  create("Adopted a pet rock and took good care of it", "Nice", "Responsible pet ownership.", "🗿"),
  create("Glued a coin to the sidewalk to trick people", "Naughty", "Prankster behavior.", "🪙"),
  create("Made a friendship bracelet for the mailman", "Nice", "Community building.", "🧶"),
  create("Used the curtains as a superhero cape", "Naughty", "Drapery damage.", "🦸"),

  // --- MODERN PROBLEMS ---
  create("Deleted Dad's save file on the video game", "Naughty", "Unforgivable digital crime.", "💾"),
  create("Liked all of Mom's photos on Instagram", "Nice", "Boosting confidence.", "📱"),
  create("Spent $500 on in-app purchases without asking", "Naughty", "Unauthorized spending.", "💳"),
  create("Taught Grandpa how to use emojis", "Nice", "Bridging the generational gap.", "👴"),
  create("Changed the Netflix password and forgot it", "Naughty", "Locked everyone out.", "📺"),
  create("Used ChatGPT to write their thank you notes", "Naughty", "Impersonal gratitude.", "🤖"),
  create("Created a viral dance video", "Nice", "Spreading entertainment.", "💃"),
  create("Prank called the pizza place", "Naughty", "Wasted pepperoni time.", "🍕"),
  create("Helped fix the Wi-Fi router", "Nice", "Tech support hero.", "📶"),
  create("Spoiled the ending of a movie for everyone", "Naughty", "Spoiler alert: that's mean.", "🎬"),

  // --- PETS & ANIMALS ---
  create("Chased the ducks at the park", "Naughty", "Stressful for the ducks.", "🦆"),
  create("Built a shelter for a stray hedgehog", "Nice", "Kindness to wildlife.", "🦔"),
  create("Barking back at the neighbor's dog all night", "Naughty", "Disturbing the peace.", "🐕"),
  create("Giving the cat a bath when it didn't need one", "Naughty", "Claws everywhere.", "🛁"),
  create("Sharing their umbrella with a dog in the rain", "Nice", "Wholesome moment.", "☂️"),
  create("Putting shoes on the horse", "Nice", "If they fit? No, wait, horses wear shoes. Good job.", "🐎"),
  create("Trying to ride the family dog like a pony", "Naughty", "Bad for the dog's back.", "🐕"),
  create("Feeding the hamster gourmet cheese", "Nice", "Culinary treat.", "🐹"),
  create("Painting the turtle's shell pink", "Naughty", "Graffiti on nature.", "🐢"),
  create("Rescuing a spider instead of squishing it", "Nice", "Respect for life.", "🕷️"),

  // --- FOOD CRIMES ---
  create("Dipped pizza in milk", "Naughty", "Culinary abomination.", "🥛"),
  create("Ate the crusts off all the sandwiches", "Nice", "Helpful disposal?", "🍞"),
  create("Double dipped a chip at a party", "Naughty", "Germ spreader.", "🥔"),
  create("Made breakfast in bed for parents (burnt toast)", "Nice", "It's the thought that counts.", "🍳"),
  create("Put ketchup on a steak", "Naughty", "Insult to the chef.", "🥩"),
  create("Shared their popcorn at the movies", "Nice", "Generous snacker.", "🍿"),
  create("Drank straight from the juice carton", "Naughty", "Hygiene violation.", "🧃"),
  create("Baked cookies for the fire department", "Nice", "Supporting local heroes.", "🚒"),
  create("Threw vegetables behind the sofa", "Naughty", "Creating a compost pile indoors.", "🥦"),
  create("Ate a lemon without making a face", "Nice", "Impressive stoicism.", "🍋"),

  // --- SCHOOL DAYS ---
  create("Passed notes during the exam", "Naughty", "Academic dishonesty.", "📝"),
  create("Tutored a classmate in math", "Nice", "Peer support.", "➕"),
  create("Put a whoopee cushion on the teacher's chair", "Naughty", "Classic, but disruptive.", "💨"),
  create("Stayed late to help clean the blackboard", "Nice", "Teacher's pet behavior.", "🧽"),
  create("Forged a signature on a permission slip", "Naughty", "Fraud.", "✍️"),
  create("Invited the lonely kid to sit at lunch", "Nice", "Inclusion champion.", "🤝"),
  create("Chewed gum loudly in the library", "Naughty", "Volume violation.", "🍬"),
  create("Returned a lost library book found outside", "Nice", "Respect for literature.", "📚"),
  create("Copied homework from Wikipedia", "Naughty", "Plagiarism.", "🌐"),
  create("Organized a school recycling program", "Nice", "Green leader.", "♻️"),

  // --- SIBLINGS & FAMILY ---
  create("Scared their brother with a realistic spider", "Naughty", "Terror tactics.", "🕷️"),
  create("Let their sister win at Mario Kart", "Nice", "Self-sacrifice.", "🏎️"),
  create("Blamed the dog for a broken vase", "Naughty", "Scapegoating the innocent.", "🏺"),
  create("Made soup for sick mom", "Nice", "Nurturing.", "🥣"),
  create("Recorded sister singing in the shower and posted it", "Naughty", "Privacy invasion.", "🎤"),
  create("Helped dad find the remote", "Nice", "Solving daily mysteries.", "📺"),
  create("Hid the remote just to watch dad panic", "Naughty", "Psychological warfare.", "🕵️"),
  create("Wore their brother's favorite shirt without asking", "Naughty", "Wardrobe theft.", "👕"),
  create("Complimented mom's new haircut", "Nice", "Observant and kind.", "💇‍♀️"),
  create("Left Legos on the floor in the dark hallway", "Naughty", "Setting a painful trap.", "🧱"),

  // --- HOLIDAY SPECIFIC ---
  create("Peeked at presents early", "Naughty", "Ruining the surprise.", "🎁"),
  create("Left carrots for the reindeer", "Nice", "Thinking of the animals.", "🥕"),
  create("Unraveled the Christmas tree lights into a knot", "Naughty", "Causing chaos.", "💡"),
  create("Helped hang the ornaments carefully", "Nice", "Decorator assistant.", "🎄"),
  create("Ate the gingerbread house roof", "Naughty", "Structural damage.", "🏠"),
  create("Sang carols to the elderly neighbors", "Nice", "Spreading cheer.", "🎶"),
  create("Knocked over the Christmas tree chasing the cat", "Naughty", "Holiday disaster.", "🐈"),
  create("Wrapped empty boxes to trick siblings", "Naughty", "Cruel prank.", "📦"),
  create("Donated their favorite toy to a toy drive", "Nice", "True spirit of Christmas.", "🧸"),
  create("Drank all the eggnog", "Naughty", "Gluttony.", "🥛"),

  // --- RANDOM & ABSURD ---
  create("Tried to dig a hole to China", "Nice", "Ambitious geography project.", "🌏"),
  create("Filled the bathtub with Jello", "Naughty", "Plumbing nightmare.", "🛁"),
  create("Talked to plants to help them grow", "Nice", "Botanical encouragement.", "🌿"),
  create("Put stickers on the sleeping dad's face", "Naughty", "Vandalizing a parent.", "🏷️"),
  create("Wore a superhero costume to church", "Nice", "Ready to save souls.", "🦸"),
  create("Tried to sell the younger brother for magic beans", "Naughty", "Human trafficking attempt.", "🌱"),
  create("Convinced the neighborhood that aliens landed", "Naughty", "Mass hysteria.", "👽"),
  create("Cleaned up litter in the park", "Nice", "Eco-warrior.", "🗑️"),
  create("Put salt in the sugar bowl", "Naughty", "The classic switcheroo.", "🧂"),
  create("Tried to heal a broken stick with a band-aid", "Nice", "Optimistic medicine.", "🩹"),

  // --- MORE SCENARIOS TO REACH 200+ ---
  create("Gave a hug to a sad friend", "Nice", "Emotional support.", "🫂"),
  create("Snipped the whiskers off the cat", "Naughty", "Disoriented the feline.", "🐱"),
  create("Used mom's lipstick to draw on the mirror", "Naughty", "Cosmetic vandalism.", "💄"),
  create("Held the door open for strangers", "Nice", "Chivalry lives.", "🚪"),
  create("Threw a snowball at the mail truck", "Naughty", "Postal interference.", "❄️"),
  create("Shoveled the neighbor's driveway", "Nice", "Snow angel.", "☃️"),
  create("Put ice cubes down someone's shirt", "Naughty", "Cold hearted.", "🧊"),
  create("Made a bird feeder out of a pinecone", "Nice", "Bird lover.", "🐦"),
  create("Screamed 'Shark!' at the public pool", "Naughty", "Causing panic.", "🦈"),
  create("Helped carry groceries in", "Nice", "Strong helper.", "🛍️"),
  create("Refused to eat anything green", "Naughty", "Vegetable discrimination.", "🥗"),
  create("Drew a smiley face on a dusty car", "Nice", "Spreading joy, technically.", "🚗"),
  create("Put a 'Kick Me' sign on someone's back", "Naughty", "Bullying behavior.", "📝"),
  create("Shared their umbrella", "Nice", "Keeping others dry.", "☔"),
  create("Told a funny joke to cheer someone up", "Nice", "Comedian.", "🤡"),
  create("Left wet towels on the bed", "Naughty", "Mildew maker.", "🧖"),
  create("Made the bed perfectly", "Nice", "Hotel quality.", "🛏️"),
  create("Stole a balloon on Free Balloon Day", "Naughty", "Wait... stole on free day?", "🎈"),
  create("Returned extra change to the cashier", "Nice", "Honesty.", "🪙"),
  create("Put empty milk carton back in fridge", "Naughty", "Lazy.", "🥛"),
  create("Called grandma just to say hi", "Nice", "Thoughtful.", "👵"),
  create("Spilled juice and covered it with a rug", "Naughty", "Cover-up operation.", "🧃"),
  create("Helped a bug flip over", "Nice", "Micro-hero.", "🐞"),
  create("Used all the hot water", "Naughty", "Resource hog.", "🚿"),
  create("Said 'please' and 'thank you'", "Nice", "Polite.", "🗣️"),
  create("Talked during the movie", "Naughty", "Cinema sinner.", "🤫"),
  create("Recycled a soda can", "Nice", "Eco-friendly.", "♻️"),
  create("Littered a candy wrapper", "Naughty", "Polluter.", "🗑️"),
  create("Complimented a stranger", "Nice", "Kind.", "😊"),
  create("Pointed and laughed", "Naughty", "Rude.", "👇"),
  create("Let someone go ahead in line", "Nice", "Patient.", "🚶"),
  create("Cut in line", "Naughty", "Impatient.", "🏃"),
  create("Cleaned the dishes", "Nice", "Helpful.", "🍽️"),
  create("Left dishes in the sink for 3 days", "Naughty", "Gross.", "🤢"),
  create("Fed the birds", "Nice", "Nature lover.", "🕊️"),
  create("Chased the pigeons", "Naughty", "Bird bothersome.", "🏃‍♂️"),
  create("Gave a gift anonymously", "Nice", "Secret Santa.", "🎁"),
  create("Regifted a used gift card", "Naughty", "Cheap.", "💳"),
  create("Listened to parents", "Nice", "Obedient.", "👂"),
  create("Ignored chores", "Naughty", "Lazy.", "🎮"),
  create("Brushed teeth", "Nice", "Hygenic.", "🦷"),
  create("Faked brushing teeth by wetting brush", "Naughty", "Deceptive hygiene.", "💧"),
  create("Went to bed on time", "Nice", "Responsible.", "😴"),
  create("Stayed up playing games till 3am", "Naughty", "Sleep deprived.", "🕹️"),
  create("Did homework early", "Nice", "Proactive.", "📓"),
  create("Hid homework under bed", "Naughty", "Avoidant.", "🙈"),
  create("Said sorry first", "Nice", "Peacemaker.", "🤝"),
  create("Held a grudge", "Naughty", "Stubborn.", "😠"),
  create("Shared dessert", "Nice", "Sweet.", "🍰"),
  create("Stole the cherry on top", "Naughty", "Greedy.", "🍒"),
  create("Walked the dog", "Nice", "Responsible.", "🐕"),
  create("Let the dog out and didn't watch it", "Naughty", "Negligent.", "🚪"),
  create("Cleaned up dog poop", "Nice", "Dirty job done well.", "💩"),
  create("Left dog poop on neighbor's lawn", "Naughty", "Rude neighbor.", "🏡"),
  create("Visited sick friend", "Nice", "Loyal.", "🤒"),
  create("Ignored friend's text", "Naughty", "Ghosting.", "👻"),
  create("Made lemonade stand for charity", "Nice", "Entrepreneur.", "🍋"),
  create("Sold tap water as 'Magic Water'", "Naughty", "Scammer.", "💧"),
  create("Picked up trash", "Nice", "Citizen.", "🗑️"),
  create("Threw gum on sidewalk", "Naughty", "Sticky situation.", "🍬"),
  create("Helped carry heavy box", "Nice", "Strong.", "📦"),
  create("Watched someone struggle with box", "Naughty", "Unhelpful.", "👀"),
  create("Gave up seat on bus", "Nice", "Gentleman/Lady.", "🚌"),
  create("Put bag on empty seat on crowded bus", "Naughty", "Space hog.", "🎒"),
  create("Smiled at everyone", "Nice", "Cheerful.", "😄"),
  create("Frowned all day", "Naughty", "Grumpy.", "☹️"),
  create("Made family laugh", "Nice", "Joyful.", "😂"),
  create("Made fun of family member", "Naughty", "Mean.", "🤡"),
  create("Kept a secret", "Nice", "Trustworthy.", "🔒"),
  create("Spilled the beans", "Naughty", "Blabbermouth.", "🙊"),
  create("Protected younger sibling", "Nice", "Protector.", "🛡️"),
  create("Teased younger sibling", "Naughty", "Bully.", "😝"),
  create("Found wallet and returned it", "Nice", "Honest.", "👛"),
  create("Found wallet and kept cash", "Naughty", "Thief.", "💸"),
  create("Told the truth when it was hard", "Nice", "Brave.", "🦁"),
  create("Lied to get out of trouble", "Naughty", "Cowardly.", "🤥"),
  create("Cheered for losing team", "Nice", "Sportsmanship.", "📣"),
  create("Booed the winner", "Naughty", "Sore loser.", "👎"),
  create("Sent a thank you card", "Nice", "Grateful.", "💌"),
  create("Complained about a gift", "Naughty", "Ungrateful.", "😒"),
  create("Learned a new skill", "Nice", "Growth mindset.", "🧠"),
  create("Refused to try new things", "Naughty", "Closed minded.", "🙅"),
  create("Helped cook dinner", "Nice", "Chef assistant.", "🍳"),
  create("Complained about the food", "Naughty", "Picky eater.", "🤢"),
  create("Saved a bee from water", "Nice", "Life saver.", "🐝"),
  create("Pulled wings off a fly", "Naughty", "Cruel.", "🪰"),
  create("Gave warm coat to homeless", "Nice", "Charitable.", "🧥"),
  create("Laughed at someone's misfortune", "Naughty", "Schadenfreude.", "😆"),
  create("Organized books", "Nice", "Tidy.", "📚"),
  create("Rip pages out of book", "Naughty", "Vandal.", "📄"),
  create("Offered a tissue to sneeze", "Nice", "Considerate.", "🤧"),
  create("Sneezed without covering mouth", "Naughty", "Germ sprayer.", "💦"),
  create("Wiped feet before entering", "Nice", "Clean.", "👣"),
  create("Tracked mud on carpet", "Naughty", "Messy.", "👞"),
  create("Turned off lights when leaving room", "Nice", "Energy saver.", "💡"),
  create("Left all lights on", "Naughty", "Wasteful.", "🕯️"),
  create("Used reusable bottle", "Nice", "Sustainable.", "🍶"),
  create("Used 10 plastic bottles a day", "Naughty", "Wasteful.", "🥤"),
  create("Fixed a broken toy", "Nice", "Repairman.", "🔧"),
  create("Broke a toy on purpose", "Naughty", "Destructive.", "🔨"),
  create("Encouraged a friend", "Nice", "Supportive.", "👏"),
  create("Discouraged a friend", "Naughty", "Toxic.", "👎"),
  create("Waited for turn", "Nice", "Patient.", "⏳"),
  create("Pushed to front", "Naughty", "Aggressive.", "😤"),
  create("Did chores without reward", "Nice", "Altruistic.", "✨"),
  create("Demanded money for chores", "Naughty", "Mercenary.", "💰"),
  create("Gave honest compliment", "Nice", "Sweet.", "🥰"),
  create("Gave backhanded compliment", "Naughty", "Snarky.", "😼"),
  create("Read instructions first", "Nice", "Smart.", "📖"),
  create("Broke it by forcing it", "Naughty", "Brute force.", "💥"),
  create("Listened without interrupting", "Nice", "Respectful.", "🤐"),
  create("Interrupted constantly", "Naughty", "Rude.", "🗣️"),
  create("Accepted apology", "Nice", "Forgiving.", "🕊️"),
  create("Refused apology", "Naughty", "Cold.", "❄️"),
  create("Worked hard on project", "Nice", "Diligent.", "🏗️"),
  create("Did minimum effort", "Naughty", "Slacker.", "🛋️"),
  create("Cleaned up someone else's mess", "Nice", "Saint.", "😇"),
  create("Made a mess and left", "Naughty", "Piggy.", "🐷"),
  create("Gave directions to lost person", "Nice", "Helpful.", "🗺️"),
  create("Gave wrong directions for fun", "Naughty", "Evil.", "😈"),
  create("Held elevator door", "Nice", "Courteous.", "🚪"),
  create("Pressed close button on elevator", "Naughty", "Antisocial.", "🔘")
];

// Shuffle helper
export const getShuffledScenarios = () => {
  return [...SCENARIOS].sort(() => Math.random() - 0.5);
};